# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Cambiamos el puerto por defecto para que no choque con otros servicios
server.port=8087
spring.application.name=QA Monitor Backend

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/qamonitor_db
spring.datasource.username=postgres
spring.datasource.password=72200571@
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# 'update' le dice a Java: Si la tabla no existe, créala. Si ya existe, actualiza las columnas.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite ver en la consola las sentencias SQL que Java genera por debajo (útil para QA)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true